### ISSUE TITLE
In HW readme, please add command for how to run your scripts. So as all the future HOs.

### ISSUE THREAD

**Issue by dichen001** [sbiswas4/FSS17_grp_J#1]
Also, it's preferred to separate data and scripts.

**Comment by sbiswas4** [comment]
Updated the Readme with how to run the script. Separated data and script by creating a data folder under HW1.

**Comment by dichen001** [comment]
Your raedme.md is not in markdown format. It also not clear and concise to read. Please follow the format of the example readme I posted on slack for future hws.

BTW, please close the issues when fixed.

**Comment by pranita-s** [comment]
Formatted the Readme.md file according to the requirements
